"Enable Client" = true

[Client]
	#Misc client side changes
	"Enable Misc" = true
	#Makes fog less invasive in some contexts
	"Enable Fog" = true
	#Changes to death
	"Enable Death" = true
	#Changes to sounds and music. Disabling this feature requires a Minecraft restart.
	"Enable Sounds & Music" = true
	#Changes to light
	"Enable Light" = true
	#Adds various infos on top left of the screen
	"Enable HUD Infos" = true
	#World border changes
	"Enable World Border" = true

	#Misc client side changes
	[Client.Misc]
		#If true, the outline around blocks will be red if the tool in hand will make drops not ... drop.
		"Red block outline with wrong tool" = true
		#Moves the hotbar this amount of pixels up (like bedrock edition). Other mods' GUI elements should work flawlessly if using the correct Forge GUI fields
		#Range: > 0
		"Floaty hotbar" = 2
		#If true, camera will not tilt when taking magic, wither, on fire, cramming, drowning and thorns damage.
		"No tilting with non directional damage types" = true
		#If true, hunger will be rendered even when the player is in riding an entity. Also hides the jump bar unless jumping (showing the XP bar)
		"Fix mounts gui" = true

	#Makes fog less invasive in some contexts
	[Client.Fog]
		#If true you'll be able to see better in lava when with the Fire Resistance Effect.
		"Better visibility in Lava with Fire Resistance Lava" = true
		#If true Nether Fog is no longer limited to 12 chunks.
		"Better nether fog" = true
		#Render distance is multiplied by this value in the Nether. Vanilla is 0.5.
		#Range: 0.0 ~ 1.0
		"Nether fog ratio" = 0.75
		#If true, overworld fog will be use the values from the config.
		"Overworld fog" = true

		[Client.Fog.Overworld]
			#Changes fog to start closer to the player. E.g. A value of 0.5 makes fog start at half the render distance. Vanilla is 1, Pre-1.18.1 was 0.75, Pre-1.7.2 was 0.25. This disables itself if Foggy Weather is enabled.
			#Range: 0.0 ~ 1.0
			"Fog start ratio" = 0.4
			#Changes fog ratio when raining. Vanilla is 1. This disables itself if Foggy Weather is enabled.
			#Range: -1.7976931348623157E308 ~ 1.0
			"Fog start ratio on rain" = -0.2

	#Changes to death
	[Client.Death]
		#If true, when you die, you switch to third person camera.
		"Third person" = true
		#Why is that still a thing?.
		"Remove score" = true
		"Replace score with time since last death" = true

	#Changes to sounds and music. Disabling this feature requires a Minecraft restart.
	[Client."Sounds & Music"]
		#Multiplies the time it takes for music to play by this value (in vanilla, normal music plays each 10 to 20 minutes).
		#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
		"Music delay multiplier" = 0.1

	#Changes to light
	[Client.Light]
		#If enabled, the brightness will be set to this value, ignoring the brightness in video settings.
		#Range: -1.0 ~ 1.0
		"Force brightness" = 0.15
		#How many ticks before expiring Night Vision will slowly fade out? Set to -1 to disable
		#Range: > -1
		"Night vision fade out time" = 50
		#If true, 'Force brightness' will only apply if the current brightness is higher than 'Force brightness'
		"Force only lower brightness" = true

	#Adds various infos on top left of the screen
	[Client."HUD Infos"]
		#If true, items in the iguanatweaksreborn:hud/season will display the current season. Only available if Serene Seasons is installed
		Season = true
		#If true, items in the iguanatweaksreborn:hud/depth will display the current Y level
		Depth = true
		#If true, items in the iguanatweaksreborn:hud/time will display the time of day
		Time = true
		#If true, items in the iguanatweaksreborn:hud/biome will display the current biome
		Biome = true
		#If true, items in the iguanatweaksreborn:hud/cardinal_direction will display the cardinal direction.
		"Cardinal direction" = true

	#World border changes
	[Client."World Border"]
		#Multiplies the height of the world border by this value. In vanilla the world border height is dependant on the render distance (in blocks) * 4. Set to 0 to disable.
		#Range: -1.0 ~ 1.0
		"Height multiplier" = 0.25
		#Set the max height of the world border.
		#Range: 1.0 ~ 1.7976931348623157E308
		"Cap height" = 128.0
		#Multiplies the world border transparency by this value
		#Range: 0.0 ~ 1.0
		Transparency = 0.4

